# Generated by Django 4.2.11 on 2025-10-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['movie', 'row', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.movie'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', help_text='Row letter, e.g. A, B, C', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('movie', 'row', 'number')},
        ),
    ]
